from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ThemeTokens:
    """Single Python mirror of the QML dashboard palette.

    ``test_qml_theme_matches_python_presentation_tokens`` keeps the QML shell
    and Python syntax highlighter aligned whenever palette constants change.
    """

    app_background: str = "#101214"
    activity_background: str = "#171a1d"
    panel_background: str = "#1c2023"
    editor_background: str = "#171a1d"
    header_background: str = "#171a1d"
    status_background: str = "#141619"
    card_background: str = "#202427"
    card_raised: str = "#292d31"
    card_hover: str = "#2b3034"
    list_hover: str = "#2b3034"
    list_active: str = "#343a3f"
    control_background: str = "#24282c"
    control_hover: str = "#30353a"
    input_background: str = "#15191c"
    input_focus: str = "#242a2f"
    border_color: str = "#363b40"
    border_subtle: str = "#2b2f33"
    text_color: str = "#eeeeee"
    muted_text: str = "#b4b7ba"
    dim_text: str = "#85898d"
    diff_context_text: str = "#888888"
    accent_blue: str = "#ff5358"
    accent_blue_hover: str = "#ff6b70"
    accent_blue_pressed: str = "#e64349"
    action_execute: str = "#3B82F6"
    action_execute_hover: str = "#60A5FA"
    action_execute_pressed: str = "#2563EB"
    action_save: str = "#35B779"
    action_save_hover: str = "#4CC98D"
    action_save_pressed: str = "#25885A"
    action_cancel: str = "#E05252"
    action_cancel_hover: str = "#F06A6A"
    action_cancel_pressed: str = "#B9363E"
    neutral_action: str = "#30363D"
    neutral_action_hover: str = "#3A424B"
    neutral_action_pressed: str = "#252B31"
    accent_green: str = "#f7b733"
    accent_green_hover: str = "#ffc64d"
    accent_green_pressed: str = "#dc9d1f"
    accent_red: str = "#ff5358"
    accent_red_hover: str = "#ff6b70"
    accent_red_pressed: str = "#d94147"
    warning_color: str = "#ffb52b"
    ok_color: str = "#54d39a"
    selection_color: str = "#4a4f54"
    scrim_color: str = "#090a0b"
    white: str = "#ffffff"
    black: str = "#0a0b0c"
    filter_teal: str = "#42c6b4"
    filter_lavender: str = "#a78bfa"
    filter_amber: str = "#f7b733"
    filter_coral: str = "#ff7b72"
    filter_sky: str = "#52b6ff"
    filter_peach: str = "#ff8f66"
    filter_mint: str = "#59d2b6"
    filter_violet: str = "#b99aff"
    visual_table: str = "#59d2b6"
    visual_chart: str = "#ffba3b"
    visual_line: str = "#6ea8fe"
    visual_pie: str = "#ba8cff"
    visual_slicer: str = "#ff8f66"
    visual_other: str = "#b4b7ba"
    control_text: str = "#8fc5ff"
    control_number: str = "#ffca6a"
    control_opacity: str = "#b99aff"
    control_color: str = "#59d2b6"
    control_boolean: str = "#ff8f99"
    history_current: str = "#1d8f9d"
    history_previous: str = "#2b8b66"
    history_future: str = "#a64f61"

    # Python-only syntax tokens use the same dashboard contrast principles.
    syntax_key: str = "#8fc5ff"
    syntax_string: str = "#f7c66f"
    syntax_number: str = "#ffca6a"
    syntax_literal: str = "#b99aff"
    syntax_punctuation: str = "#c7d0d9"


DEFAULT_THEME = ThemeTokens()
